export const CHANGE_USER_PROFILE_DATA = "CHANGE_USER_PROFILE_DATA";
export const CHANGE_USER_PROVIDER_DATA = "CHANGE_USER_PROVIDER_DATA";
export const CHANGE_PROVIDER_ROLE_DATA = "CHANGE_PROVIDER_ROLE_DATA";
export const CHANGE_CURRENT_ROLE = "CHANGE_CURRENT_ROLE";
export const CHANGE_PROVIDER_EMAIL_DATA = "CHANGE_PROVIDER_EMAIL_DATA";